name: Bundle and deploy
on:
  push:
    branches: ["rebel-fury"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: one
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build 🔧
        run: |
          npm i -g pnpm 
          pnpm i
          pnpm run build
      - name: Deploy
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'https://rebel-fury.surge.sh'
          project: 'dist'
          login: 'rzymek@gmail.com'
          token: ${{ secrets.surge_token }}